export const styles = {
  section: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "100vh",
    position: "relative",
    background: "linear-gradient(to right, #d9dbde, #242738)",
    overflow: "hidden",
  },
  left: {
    backgroundColor: "#d9dbde",
    flex: 1,
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "100px",
    color: "white",
    boxShadow: "inset 0 0 10px rgba(0, 0, 0, 0.2)",
    transition: "box-shadow 0.3s ease, background-color 0.3s ease", 
  },
  right: {
    backgroundColor: "#242738",
    flex: 1,
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "100px",
    color: "white",
    boxShadow: "inset 0 0 10px rgba(255, 255, 255, 0.2)",
    transition: "box-shadow 0.3s ease, background-color 0.3s ease", // No transform here
  },
  s: {
    position: "absolute",
    top: "50%",
    left: "53%",
    transform: "translate(-60%, -50%)",
    zIndex: 5,
    width: "48%",
    height: "80%",
    filter: "drop-shadow(0px 10px 20px rgba(0, 0, 0, 0.5))",
  },
  letter: {
    fontSize: "90px",
    fontWeight: "900",
    textAlign: "center",
    zIndex: 5,
    textShadow: "2px 2px 5px rgba(0, 0, 0, 0.5)",
    transition: "all 0.3s ease",
  },
  letterHover: {
    color: "#5b5a5e",
    textShadow: "5px 5px 15px #e8a166",
    transform: "scale(1.1)",
  },
};
